### ISSUE TITLE
MalformedIndentationError while parsing haml containing conditional comment

### ISSUE THREAD

**Issue by eggplants** [r7kamura/rubocop-haml#7]
I got an error when trying to format the haml for [HTML emails](https://en.wikipedia.org/wiki/HTML_email) used in [Action Mailer](https://guides.rubyonrails.org/action_mailer_basics.html).

## MRE 

https://gist.github.com/eggplants/5d1fed8f94ef08e616f5e404c3f34a31

## Error code

```haml
-# https://stackoverflow.design/email/base/mso/
-# https://haml.info/docs/yardoc/file.REFERENCE.html#conditional-comments-
-# https://www.quirksmode.org/css/condcom.html
%div{:style => "..."}
  .block-grid{:style => "..."}
    %div{:style => "..."}
      /[if (mso)|(IE)] <table width="100%"><tr><td style="..."><table><tr style="...">
      -# snip
      Hoge Fuga
      -# snip
      /[if (mso)|(IE)] </td></tr></table>
```

compiles to ([haml](https://rubygems.org/gems/haml) 6.1.1, `haml render example.html.haml`):

```html
<div style='...'>
<div class='block-grid' style='...'>
<div style='...'>
<!--[if (mso)|(IE)]> <table width="100%"><tr><td style="..."><table><tr style="..."> <![endif]-->
Hoge Fuga
<!--[if (mso)|(IE)]> </td></tr></table> <![endif]-->
</div>
</div>
</div>
```

## Error log

```shellsession
$ bundle exec rubocop
MalformedIndentationError at /home/eggplants/prog/rubocop-haml-ie-comment-issue/example.html.haml:7:24
      /[if (mso)|(IE)] <table width="100%"><tr><td style="..."><table><tr style="...">
                       ^
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/hamli-0.5.1/lib/hamli/parser.rb:481:in `syntax_error!'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/hamli-0.5.1/lib/hamli/parser.rb:96:in `parse_indent'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/hamli-0.5.1/lib/hamli/parser.rb:31:in `parse_block'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/hamli-0.5.1/lib/hamli/parser.rb:22:in `call'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rubocop-haml-649a1b313640/lib/rubocop/haml/ruby_extractor.rb:50:in `ast'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rubocop-haml-649a1b313640/lib/rubocop/haml/ruby_extractor.rb:62:in `ruby_ranges'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rubocop-haml-649a1b313640/lib/rubocop/haml/ruby_extractor.rb:27:in `call'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rubocop-haml-649a1b313640/lib/rubocop/haml/ruby_extractor.rb:14:in `call'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:359:in `block in extract_ruby_sources'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:358:in `each'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:358:in `find'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:358:in `extract_ruby_sources'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:343:in `inspect_file'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:314:in `loop'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:163:in `file_offenses'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:99:in `block in warm_cache'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:627:in `call_with_index'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:597:in `process_incoming_jobs'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:577:in `block in worker'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `fork'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `worker'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:559:in `block in create_workers'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each_with_index'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `create_workers'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:497:in `work_in_processes'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:291:in `map'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:235:in `each'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:99:in `warm_cache'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/runner.rb:72:in `run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli/command.rb:11:in `run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli.rb:118:in `run_command'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli.rb:125:in `execute_runners'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli.rb:51:in `block in run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/lib/rubocop/cli.rb:43:in `run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/exe/rubocop:19:in `block in <top (required)>'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.51.0/exe/rubocop:19:in `<top (required)>'
/home/eggplants/.rbenv/versions/3.2.2/bin/rubocop:25:in `load'
/home/eggplants/.rbenv/versions/3.2.2/bin/rubocop:25:in `<top (required)>'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `load'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:23:in `run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:492:in `exec'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:34:in `dispatch'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:28:in `start'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/exe/bundle:45:in `block in <top (required)>'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/eggplants/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/exe/bundle:33:in `<top (required)>'
/home/eggplants/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/home/eggplants/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

```

**Comment by r7kamura** [comment]
Thank you @eggplants for reporting! This certainly seems to be a bug.
Since the official [haml](https://github.com/haml/haml) implementation does not have the ability to return positional information when parsing, rubocop-haml is using another parser implementation I created called [hamli](https://github.com/r7kamura/hamli), which I suspect does not support comment notation. So I think a good solution for this issue would be to add an implementation to hamli that supports comment notation. 🤔

**Comment by eggplants** [comment]
I created more small example.

NG:

```haml
%div
  /[if (mso)|(IE)] <table><tr><td>
  a
  /[if (mso)|(IE)] </td></tr></table>
```

OK:

```haml
/[if (mso)|(IE)] <table><tr><td>
a
/[if (mso)|(IE)] </td></tr></table>
```

**Comment by r7kamura** [comment]
I could reproduce the reported error as a RSpec test case on hamli .

```diff
diff --git a/spec/hamli/parser_spec.rb b/spec/hamli/parser_spec.rb
index e38419b..b9b0323 100644
--- a/spec/hamli/parser_spec.rb
+++ b/spec/hamli/parser_spec.rb
@@ -355,6 +355,19 @@ RSpec.describe Hamli::Parser do
       end
     end
 
+    context 'with HTML conditional comment' do
+      let(:source) do
+        <<~HAML
+          %div
+            /[if IE] <br>
+        HAML
+      end
+
+      it 'returns expected S-expression' do
+        subject
+      end
+    end
+
     context 'with Haml comment' do
       let(:source) do
         <<~HAML
```

```
Failures:

  1) Hamli::Parser#call with HTML conditional comment returns expected S-expression
     Failure/Error:
       raise syntax_error_class.new(
         column: range.column,
         file_path: @file_path,
         line: range.line,
         line_number: range.line_number
       )
     
     Hamli::Errors::MalformedIndentationError:
       MalformedIndentationError at (__TEMPLATE__):2:12
         /[if IE] <br>
                  ^
     # ./lib/hamli/parser.rb:481:in `syntax_error!'
     # ./lib/hamli/parser.rb:96:in `parse_indent'
     # ./lib/hamli/parser.rb:31:in `parse_block'
     # ./lib/hamli/parser.rb:22:in `call'
     # ./spec/hamli/parser_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./spec/hamli/parser_spec.rb:367:in `block (4 levels) in <top (required)>'

Finished in 0.00858 seconds (files took 0.05506 seconds to load)
```

Since this seems clearly a problem at hamli, I will transfer this issue to hamli repository.
